05 cz narrative
OtagoPolytechnic/forth-street-studios-s1-24-team-1 pull request #101
Opened 2024-05-30 01:20 UTC by Carlson-Lee

2024-05-31 03:03 UTC, Carlson-Lee commented
A little heads up with the triple pop-ups with the buildings, central buildings and bonus tiles. I was trying to trigger them individually, but I couldn't get that done properly.
![image](https://github.com/OtagoPolytechnic/forth-street-studios-s1-24-team-1/assets/83677521/573bd318-5864-4a01-aa2d-a76a850eff14)

2024-05-31 03:43 UTC, PBWiseman requested changes
I like the rework! Couple of minor spelling mistakes to fix then it should be good to merge. The only other thing is that there seems to be conflicting changes with Level1 scene? Not totally sure why since all your work seems to be in the Tutorial scene. Just make sure that you keep the staging changes when merging.

2024-05-31 03:43 UTC, PBWiseman commented on Assets/Scripts/TutorialManager.cs
> +        { TutorialSections.Scoreboard, "Congratulation you have score a point. - Click to Advance" },
Should be "Congratulations you have scored a point."

2024-05-31 03:43 UTC, PBWiseman commented on Assets/Scripts/TutorialManager.cs
> +        { TutorialSections.BonusTiles, "The coloured space on the tiles you see, they are bonus tiles, place an building on it for extra scores." },
Should be "a building"

2024-05-31 05:32 UTC, PBWiseman approved these changes

2024-05-31 23:48 UTC, LiamMcKenzie requested changes
the rocks at the bottom don't have any collision, this can be fixed in TutorialManager.cs

Otherwise I think this looks good

2024-06-02 01:23 UTC, ChaseBENNC9 requested changes
New Tutorial feels much better with the added narrative. well done. As mentioned already there is an issue with the obstacle's collision

2024-06-10 01:32 UTC, ChaseBENNC9 approved these changes
looks good

2024-06-10 01:44 UTC, LiamMcKenzie approved these changes
# Code Review

## Functional Requirements
_Is the application fit for purpose? Does it meet the user’s requirements and properly address the issue?_  

 - I think this is an improvement to the old tutorial
 - The changes I requested were addressed

## Legibility and Style
_Uses agreed coding standards/conventions? Readable, consistent and well-structured with useful comments?_  

 - It could have used more comments, but there are enough to understand what the bigger functions are doing.

_Any repetitive code that could be refactored? (DRY)_  

 - No repeated code from what I noticed. 
 - The code to say where buildings is looks a bit repetitive, but we've all agreed this is okay.

## Correctness of the Code
_Is the code reliable, giving same results every time it runs? Does it function correctly?_  

 - No bugs from what I noticed

## Implementation
_Any notable performance/speed issues? Compatibility and Responsiveness on other platforms ?_  

 - I noticed no speed issues.


# Final Comments

 - This is a great feature, the updated text is much easier to understand.
 - Looks good to merge into staging

***

2024-06-10 01:47 UTC, merged

2024-06-10 01:47 UTC, LiamMcKenzie commented
Merged on behalf of carlson